service: s3-video-data

provider:
  name: aws
  region: us-east-1
  runtime: python3.9
  stackName: s3-video-data
  stage: dev   
  environment:
    AccessControlAllowOrigin: ${self:custom.${self:custom.myStage}.CORSOrigin}
  logRetentionInDays: 7
  timeout: 25
  iam:
    role:
      name: s3-video-app-data
      # path: /custom-role-path/
      # statements:
      #   - Effect: 'Allow'
      #     Resource: '*'
      #     Action: 'iam:DeleteUser'
      managedPolicies:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'


functions:

  VideoDataManagement:
    handler: upload.lambda_handler
    name: VideoDataManagement
    events:
      - http:
          cors:
            origins:
              - ${self:custom.${self:custom.myStage}.CORSOriginAPI}
          path: data/
          method: POST
