service: s3-video-data

custom:
  CORSOrigin: '*'

provider:
  name: aws
  region: us-east-1
  runtime: python3.9
  stackName: s3-video-data
  stage: dev   
  environment:
    AccessControlAllowOrigin: ${self:custom.CORSOrigin}
  logRetentionInDays: 7
  timeout: 25
  apiGateway:
    binaryMediaTypes:
      # - '*/*'
      # - 'video/mp4'
      - 'video/*'
      - 'application/octet-stream'
  iam:
    role:
      name: s3-video-app-data
      managedPolicies:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'


functions:

  UploadVideos:
    handler: upload.lambda_handler
    name: UploadVideos
    events:
      - http:
          cors:
            origins:
              - ${self:custom.CORSOrigin}
          path: data/
          method: POST

  CancelVideoUpload:
    handler: upload.lambda_handler
    name: CancelVideoUpload
    events:
      - http:
          cors:
            origins:
              - ${self:custom.CORSOrigin}
          path: data/
          method: DELETE

